steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install --force']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'rsync', '-r', '-d', 'build', 'gs://bynar-website']
